#!/usr/bin/env python3
"""
Perplexity Sonar API client for Phase 2 social-listening research.

Runs 5 parallel queries about a product and synthesizes results into research.md.

Usage:
    export PERPLEXITY_API_KEY='pplx-...'
    python3 perplexity_research.py "product_name" [--brief path/to/product-brief.md]
"""
import argparse
import concurrent.futures
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API_KEY = os.environ.get("PERPLEXITY_API_KEY")
if not API_KEY:
    print("ERROR: PERPLEXITY_API_KEY env var not set", file=sys.stderr)
    sys.exit(1)

ENDPOINT = "https://api.perplexity.ai/chat/completions"
MODEL = "sonar-pro"


def build_queries(product_name, product_category=None):
    """Build the 5 standard research queries."""
    cat = product_category or f"{product_name}'s product category"
    return [
        {
            "name": "pain_points",
            "query": (
                f"What are the most common frustrations or pain points that users voice about "
                f"{cat}? Look at recent reddit threads (r/programming, r/MachineLearning, r/LocalLLaMA), "
                f"hacker news, and twitter/X posts from the last 6 months. List the top 3-5 specific "
                f"pain points with quoted examples and source URLs."
            ),
        },
        {
            "name": "viral_angles",
            "query": (
                f"What product launch videos or posts about {cat} have gone viral on TikTok, "
                f"YouTube Shorts, X/Twitter, or Hacker News in the last 6 months? Specifically, "
                f"what was each one's hook strategy? What made viewers engage? Include URLs."
            ),
        },
        {
            "name": "competitive_context",
            "query": (
                f"Who are {product_name}'s main competitors? What do users say about them in "
                f"recent comparisons? What features or qualities do users specifically praise or "
                f"criticize about each? Include source URLs."
            ),
        },
        {
            "name": "recent_discussions",
            "query": (
                f"What did people say about {product_name} specifically in the last 30 days? "
                f"Reddit, twitter/X, hacker news, github issues. Highlight any specific features, "
                f"complaints, or surprising uses that came up multiple times. Include URLs."
            ),
        },
        {
            "name": "audience_profile",
            "query": (
                f"Based on online discussions, who is the typical user of {product_name} or {cat}? "
                f"What's their job role (engineer, PM, marketer, founder, etc.)? What language and "
                f"phrases do they use to describe their problems? What are they likely switching from?"
            ),
        },
    ]


def call_perplexity(query, timeout=90):
    """Single call to Perplexity Sonar API. Returns {content, citations, usage}."""
    payload = {
        "model": MODEL,
        "messages": [
            {
                "role": "system",
                "content": "You are a market research analyst. Be specific, cite all sources with URLs, and quote real user language where possible.",
            },
            {"role": "user", "content": query},
        ],
        "max_tokens": 2000,
        "temperature": 0.2,
    }

    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {API_KEY}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        return {
            "content": f"[API error {e.code}: {body[:200]}]",
            "citations": [],
            "usage": {},
            "error": True,
        }

    return {
        "content": data["choices"][0]["message"]["content"],
        "citations": data.get("citations", []),
        "usage": data.get("usage", {}),
        "error": False,
    }


def run_query(item):
    """Wrapper for ThreadPoolExecutor."""
    name = item["name"]
    print(f"  [{name}] querying...", file=sys.stderr)
    start = time.time()
    result = call_perplexity(item["query"])
    elapsed = time.time() - start
    status = "✗ failed" if result["error"] else "✓ done"
    print(f"  [{name}] {status} ({elapsed:.1f}s)", file=sys.stderr)
    return name, item["query"], result


def synthesize(results, product_name):
    """Build research.md from all 5 query results."""
    lines = [f"# Phase 2 research — {product_name}", ""]
    lines.append(f"_Generated by Perplexity sonar-pro at {time.strftime('%Y-%m-%d %H:%M')}_")
    lines.append("")

    section_titles = {
        "pain_points": "Top pain points",
        "viral_angles": "Viral hook patterns",
        "competitive_context": "Competitive context",
        "recent_discussions": "Recent discussions",
        "audience_profile": "Audience profile",
    }

    all_citations = set()

    for name, query, result in results:
        title = section_titles.get(name, name)
        lines.append(f"## {title}")
        lines.append("")
        lines.append(f"_Query:_ {query}")
        lines.append("")
        lines.append(result["content"])
        lines.append("")
        for cit in result["citations"]:
            all_citations.add(cit)

    lines.append("## All sources")
    lines.append("")
    for url in sorted(all_citations):
        lines.append(f"- {url}")

    return "\n".join(lines)


def calculate_cost(results):
    """Sum token usage across all queries to estimate cost."""
    total_prompt = 0
    total_completion = 0
    for _, _, r in results:
        u = r.get("usage", {})
        total_prompt += u.get("prompt_tokens", 0)
        total_completion += u.get("completion_tokens", 0)

    # sonar-pro pricing (rough): $1/1M input, $1/1M output
    # exact rates may vary; this is best-effort estimate
    cost_usd = (total_prompt + total_completion) / 1_000_000 * 1.0
    return cost_usd, total_prompt, total_completion


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("product_name", help="Name of the product to research")
    ap.add_argument("--category", help="Product category if non-obvious", default=None)
    ap.add_argument("--out", default="research.md", help="Output markdown file")
    args = ap.parse_args()

    queries = build_queries(args.product_name, args.category)
    print(f"Running {len(queries)} parallel research queries about {args.product_name}...",
          file=sys.stderr)

    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as pool:
        futures = [pool.submit(run_query, q) for q in queries]
        results = [f.result() for f in futures]

    md = synthesize(results, args.product_name)
    Path(args.out).write_text(md)

    cost_usd, in_tok, out_tok = calculate_cost(results)
    print(f"\nResearch complete:", file=sys.stderr)
    print(f"  output: {args.out}", file=sys.stderr)
    print(f"  tokens: {in_tok} in + {out_tok} out", file=sys.stderr)
    print(f"  estimated cost: ${cost_usd:.3f}", file=sys.stderr)


if __name__ == "__main__":
    main()
